var trafficeData, savePeploeData, dangerData, natureData, chemistryData, data;
trafficeData = [
    { "totalArea": '2019年全省合计', "area": "2019年全省合计", "all": "1217", "speed": "246", "nation": "68", "province": "117", "country": "364", "city": "337", },
    { "totalArea": "贵阳", "area": "小计", "all": " 271", "speed": "57", "nation": "12", "province": "13", "country": "62", "city": "127" },
    { "totalArea": "贵阳", "area": "南明区", "all": "34", "speed": "1", "nation": "0", "province": "0", "country": "1", "city": "32" },
    { "totalArea": "贵阳", "area": "云岩区", "all": "21", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "21" },
    { "totalArea": "贵阳", "area": "清镇市", "all": "32", "speed": "17", "nation": "0", "province": "0", "country": "6", "city": "9" },
    { "totalArea": "贵阳", "area": "花溪区", "all": "28", "speed": "3", "nation": "2", "province": "3", "country": "20", "city": "0" },
    { "totalArea": "贵阳", "area": "乌当区", "all": "29", "speed": "9", "nation": "6", "province": "1", "country": "4", "city": "9" },
    { "totalArea": "贵阳", "area": "白云区", "all": "30", "speed": "6", "nation": "1", "province": "1", "country": "8", "city": "14" },
    { "totalArea": "贵阳", "area": "经开区", "all": "9", "speed": "1", "nation": "0", "province": "4", "country": "0", "city": "4" },
    { "totalArea": "贵阳", "area": "开阳县", "all": "9", "speed": "7", "nation": "0", "province": "0", "country": "2", "city": "0" },
    { "totalArea": "贵阳", "area": "息烽县", "all": "10", "speed": "2", "nation": "3", "province": "0", "country": "4", "city": "1" },
    { "totalArea": "贵阳", "area": "修文县", "all": "20", "speed": "3", "nation": "0", "province": "4", "country": "8", "city": "5" },
    { "totalArea": "贵阳", "area": "观山湖区", "all": "49", "speed": "8", "nation": "0", "province": "0", "country": "9", "city": "32" },
    {
        "totalArea": "遵义",
        "area": "小计",
        "all": "237",
        "speed": "42",
        "nation": "16",
        "province": "28",
        "country": "88",
        "city": "63"
    },
    { "totalArea": "遵义", "area": "红花岗区", "all": "23", "speed": "1", "nation": "0", "province": "0", "country": "4", "city": "18" },
    { "totalArea": "遵义", "area": "汇川区", "all": "21", "speed": "5", "nation": "4", "province": "0", "country": "8", "city": "4" },
    { "totalArea": "遵义", "area": "赤水县", "all": "8", "speed": "0", "nation": "0", "province": "0", "country": "4", "city": "4" },
    { "totalArea": "遵义", "area": "新浦区", "all": "11", "speed": "1", "nation": "1", "province": "0", "country": "3", "city": "6" },
    { "totalArea": "遵义", "area": "仁怀市", "all": "26", "speed": "4", "nation": "0", "province": "0", "country": "15", "city": "7" },
    { "totalArea": "遵义", "area": "播州区", "all": "33", "speed": "6", "nation": "2", "province": "8", "country": "12", "city": "5" },
    { "totalArea": "遵义", "area": "桐梓县", "all": "17", "speed": "5", "nation": "1", "province": "4", "country": "4", "city": "3" },
    { "totalArea": "遵义", "area": "绥阳县", "all": "21", "speed": "2", "nation": "0", "province": "1", "country": "12", "city": "6" },
    { "totalArea": "遵义", "area": "正安县", "all": "15", "speed": "1", "nation": "0", "province": "7", "country": "6", "city": "1" },
    { "totalArea": "遵义", "area": "道真县", "all": "4", "speed": "1", "nation": "0", "province": "0", "country": "3", "city": "0" },
    { "totalArea": "遵义", "area": "务川县", "all": "4", "speed": "1", "nation": "0", "province": "0", "country": "3", "city": "0" },
    { "totalArea": "遵义", "area": "凤冈县", "all": "4", "speed": "0", "nation": "0", "province": "0", "country": "2", "city": "2" },
    { "totalArea": "遵义", "area": "湄潭县", "all": "26", "speed": "12", "nation": "2", "province": "1", "country": "8", "city": "3" },
    { "totalArea": "遵义", "area": "余庆县", "all": "10", "speed": "1", "nation": "0", "province": "5", "country": "2", "city": "2" },
    { "totalArea": "遵义", "area": "习水县", "all": "14", "speed": "2", "nation": "6", "province": "2", "country": "2", "city": "2" },
    {
        "totalArea": "安顺",
        "area": "小计",
        "all": "237",
        "all": "75",
        "speed": "23",
        "nation": "2",
        "province": "9",
        "country": "23",
        "city": "18"
    },
    { "totalArea": "安顺", "area": "西秀区", "all": "35", "speed": "12", "nation": "0", "province": "2", "country": "10", "city": "11" },
    { "totalArea": "安顺", "area": "黄果树开发区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "安顺", "area": "平坝县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0" },
    { "totalArea": "安顺", "area": "普定县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "安顺", "area": "关岭县", "all": "14", "speed": "7", "nation": "2", "province": "1", "country": "4", "city": "0" },
    { "totalArea": "安顺", "area": "镇宁县", "all": "7", "speed": "2", "nation": "0", "province": "1", "country": "4", "city": "0" },
    { "totalArea": "安顺", "area": "紫云县", "all": "11", "speed": "2", "nation": "0", "province": "5", "country": "2", "city": "2" },
    { "totalArea": "安顺", "area": "安顺市开发区", "all": "7", "speed": "0", "nation": "0", "province": "0", "country": "2", "city": "5" },
    {
        "totalArea": "黔南",
        "area": "小计",
        "all": "121",
        "speed": "33",
        "nation": "8",
        "province": "12",
        "country": "46",
        "city": "22"
    },
    { "totalArea": "黔南", "area": "都匀市", "all": "19", "speed": "7", "nation": "3", "province": "0", "country": "3", "city": "6" },
    { "totalArea": "黔南", "area": "福泉市", "all": "14", "speed": "4", "nation": "1", "province": "0", "country": "5", "city": "4" },
    { "totalArea": "黔南", "area": "荔波县", "all": "10", "speed": "0", "nation": "0", "province": "0", "country": "6", "city": "4" },
    { "totalArea": "黔南", "area": "贵定县", "all": "10", "speed": "2", "nation": "0", "province": "0", "country": "7", "city": "1" },
    { "totalArea": "黔南", "area": "瓮安县", "all": "13", "speed": "3", "nation": "0", "province": "4", "country": "4", "city": "2" },
    { "totalArea": "黔南", "area": "独山县", "all": "10", "speed": "5", "nation": "1", "province": "0", "country": "4", "city": "0" },
    { "totalArea": "黔南", "area": "平塘县", "all": "13", "speed": "0", "nation": "0", "province": "4", "country": "7", "city": "2" },
    { "totalArea": "黔南", "area": "罗甸县", "all": "2", "speed": "0", "nation": "0", "province": "1", "country": "1", "city": "0" },
    { "totalArea": "黔南", "area": "长顺县", "all": "4", "speed": "2", "nation": "0", "province": "0", "country": "1", "city": "1" },
    { "totalArea": "黔南", "area": "龙里县", "all": "10", "speed": "7", "nation": "1", "province": "1", "country": "0", "city": "1" },
    { "totalArea": "黔南", "area": "惠水县", "all": "4", "speed": "0", "nation": "0", "province": "0", "country": "3", "city": "1" },
    { "totalArea": "黔南", "area": "三都县", "all": "10", "speed": "1", "nation": "2", "province": "2", "country": "5", "city": "0" },
    {
        "totalArea": "黔东南",
        "area": "小计",
        "all": "49",
        "speed": "10",
        "nation": "7",
        "province": "6",
        "country": "14",
        "city": "12"
    },
    { "totalArea": "黔东南", "area": "凯里市", "all": "6", "speed": "1", "nation": "1", "province": "2", "country": "2", "city": "0" },
    { "totalArea": "黔东南", "area": "黄平县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "黔东南", "area": "施秉县", "all": "2", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "2" },
    { "totalArea": "黔东南", "area": "三穗县", "all": "3", "speed": "1", "nation": "1", "province": "0", "country": "1", "city": "0" },
    { "totalArea": "黔东南", "area": "镇远县", "all": "3", "speed": "0", "nation": "0", "province": "2", "country": "1", "city": "0" },
    { "totalArea": "黔东南", "area": "岑巩县", "all": "1", "speed": "1", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "黔东南", "area": "天柱县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0" },
    { "totalArea": "黔东南", "area": "锦屏县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0" },
    { "totalArea": "黔东南", "area": "剑河县", "all": "1", "speed": "1", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "黔东南", "area": "台江县", "all": "4", "speed": "1", "nation": "1", "province": "0", "country": "1", "city": "1" },
    { "totalArea": "黔东南", "area": "黎平县", "all": "6", "speed": "1", "nation": "0", "province": "0", "country": "4", "city": "1" },
    { "totalArea": "黔东南", "area": "榕江县", "all": "1", "speed": "0", "nation": "1", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "黔东南", "area": "从江县", "all": "7", "speed": "1", "nation": "2", "province": "0", "country": "3", "city": "1" },
    { "totalArea": "黔东南", "area": "雷山县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0" },
    { "totalArea": "黔东南", "area": "麻江县", "all": "1", "speed": "1", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "黔东南", "area": "丹寨县", "all": "6", "speed": "2", "nation": "1", "province": "0", "country": "0", "city": "3" },
    { "totalArea": "黔东南", "area": "经济开发区", "all": "5", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "4" },
    {
        "totalArea": "铜仁",
        "area": "小计",
        "all": "91",
        "speed": "27",
        "nation": "6",
        "province": "11",
        "country": "29",
        "city": "18"
    },
    { "totalArea": "铜仁", "area": "铜仁市", "all": "16", "speed": "5", "nation": "0", "province": "2", "country": "3", "city": "6" },
    { "totalArea": "铜仁", "area": "万山特区", "all": "7", "speed": "0", "nation": "2", "province": "0", "country": "3", "city": "2" },
    { "totalArea": "铜仁", "area": "江口县", "all": "7", "speed": "6", "nation": "0", "province": "1", "country": "0", "city": "0" },
    { "totalArea": "铜仁", "area": "玉屏县", "all": "4", "speed": "1", "nation": "2", "province": "0", "country": "0", "city": "1" },
    { "totalArea": "铜仁", "area": "石阡县", "all": "9", "speed": "6", "nation": "0", "province": "2", "country": "0", "city": "1" },
    { "totalArea": "铜仁", "area": "思南县", "all": "10", "speed": "3", "nation": "0", "province": "1", "country": "6", "city": "0" },
    { "totalArea": "铜仁", "area": "印江县", "all": "8", "speed": "1", "nation": "0", "province": "4", "country": "2", "city": "1" },
    { "totalArea": "铜仁", "area": "德江县", "all": "8", "speed": "4", "nation": "1", "province": "0", "country": "3", "city": "0" },
    { "totalArea": "铜仁", "area": "沿河县", "all": "4", "speed": "1", "nation": "0", "province": "0", "country": "3", "city": "0" },
    { "totalArea": "铜仁", "area": "松桃县", "all": "17", "speed": "0", "nation": "1", "province": "1", "country": "8", "city": "7" },
    { "totalArea": "铜仁", "area": "大龙经济开发区", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0" },
    {
        "totalArea": "毕节",
        "area": "小计",
        "all": "109",
        "speed": "19",
        "nation": "7",
        "province": "1",
        "country": "50",
        "city": "32"
    },
    { "totalArea": "毕节", "area": "七星关区", "all": "29", "speed": "5", "nation": "0", "province": "0", "country": "10", "city": "14" },
    { "totalArea": "毕节", "area": "大方县", "all": "16", "speed": "3", "nation": "2", "province": "0", "country": "9", "city": "2" },
    { "totalArea": "毕节", "area": "黔西县", "all": "20", "speed": "4", "nation": "4", "province": "0", "country": "8", "city": "4" },
    { "totalArea": "毕节", "area": "金沙县", "all": "2", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "1" },
    { "totalArea": "毕节", "area": "织金县", "all": "12", "speed": "2", "nation": "0", "province": "0", "country": "4", "city": "6" },
    { "totalArea": "毕节", "area": "纳雍县", "all": "9", "speed": "2", "nation": "0", "province": "1", "country": "4", "city": "2" },
    { "totalArea": "毕节", "area": "威宁县", "all": "11", "speed": "1", "nation": "1", "province": "0", "country": "6", "city": "3" },
    { "totalArea": "毕节", "area": "赫章县", "all": "10", "speed": "2", "nation": "0", "province": "0", "country": "8", "city": "0" },
    {
        "totalArea": "六盘水",
        "area": "小计",
        "all": "96",
        "speed": "22",
        "nation": "4",
        "province": "29",
        "country": "18",
        "city": "23"
    },
    { "totalArea": "六盘水", "area": "钟山区", "all": "13", "speed": "0", "nation": "0", "province": "5", "country": "1", "city": "7" },
    { "totalArea": "六盘水", "area": "六枝特区", "all": "8", "speed": "0", "nation": "0", "province": "4", "country": "2", "city": "2" },
    { "totalArea": "六盘水", "area": "水城县", "all": "41", "speed": "10", "nation": "1", "province": "15", "country": "10", "city": "5" },
    { "totalArea": "六盘水", "area": "盘县", "all": "29", "speed": "12", "nation": "3", "province": "5", "country": "3", "city": "6" },
    { "totalArea": "六盘水", "area": "红桥新区", "all": "5", "speed": "0", "nation": "0", "province": "0", "country": "2", "city": "3" },
    {
        "totalArea": "黔西南",
        "area": "小计",
        "all": "68",
        "speed": "12",
        "nation": "6",
        "province": "8",
        "country": "32",
        "city": "10"
    },
    { "totalArea": "黔西南", "area": "兴义市", "all": "20", "speed": "1", "nation": "2", "province": "1", "country": "9", "city": "7" },
    { "totalArea": "黔西南", "area": "顶效开发区", "all": "8", "speed": "2", "nation": "0", "province": "0", "country": "6", "city": "0" },
    { "totalArea": "黔西南", "area": "兴仁县", "all": "12", "speed": "3", "nation": "1", "province": "1", "country": "5", "city": "2" },
    { "totalArea": "黔西南", "area": "普安县", "all": "6", "speed": "1", "nation": "0", "province": "0", "country": "5", "city": "0" },
    { "totalArea": "黔西南", "area": "晴隆县", "all": "10", "speed": "5", "nation": "2", "province": "0", "country": "3", "city": "0" },
    { "totalArea": "黔西南", "area": "贞丰县", "all": "6", "speed": "0", "nation": "0", "province": "5", "country": "0", "city": "1" },
    { "totalArea": "黔西南", "area": "望漠县", "all": "3", "speed": "0", "nation": "0", "province": "0", "country": "3", "city": "0" },
    { "totalArea": "黔西南", "area": "册亨县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0" },
    { "totalArea": "黔西南", "area": "安龙县", "all": "2", "speed": "0", "nation": "1", "province": "1", "country": "0", "city": "0" },
    {
        "totalArea": "贵安",
        "area": "小计",
        "all": "15",
        "speed": "1",
        "nation": "0",
        "province": "0",
        "country": "2",
        "city": "12"
    },

]
dangerData = [
    {
        "totalArea": "2019年全省合计", "area": "2019年全省合计 ", "all": "200", "speed": "4", "nation": "1", "province": "138", "country": "44", "city": "3", "fire": "1", "corrosives": "1", "oxygen": "8",
    },
    { "totalArea": "贵阳", "area": "小计", "all": "0", "speed": "1", "nation": "0", "province": "83", "country": "35", "city": "3", "fire": "0", "corrosives": "0", "oxygen": "6" },
    { "totalArea": "贵阳", "area": "南明区", "all": "29", "speed": "1", "nation": "0", "province": "22", "country": "4", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "2" },
    { "totalArea": "贵阳", "area": "云岩区", "all": "26", "speed": "0", "nation": "0", "province": "17", "country": "9", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "贵阳", "area": "清镇市", "all": "7", "speed": "0", "nation": "0", "province": "6", "country": "0", "city": "1", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "贵阳", "area": "花溪区", "all": "13", "speed": "0", "nation": "0", "province": "5", "country": "8", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "贵阳", "area": "乌当区", "all": "4", "speed": "0", "nation": "0", "province": "2", "country": "2", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "贵阳", "area": "白云区", "all": "15", "speed": "0", "nation": "0", "province": "8", "country": "5", "city": "2", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "贵阳", "area": "小河区", "all": "8", "speed": "0", "nation": "0", "province": "5", "country": "2", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "1" },
    { "totalArea": "贵阳", "area": "开阳县", "all": "4", "speed": "0", "nation": "0", "province": "2", "country": "2", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "贵阳", "area": "息烽县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "贵阳", "area": "修文县", "all": "7", "speed": "0", "nation": "0", "province": "5", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "2" },
    { "totalArea": "贵阳", "area": "金阳", "all": "0", "speed": "0", "nation": "0", "province": "11", "country": "2", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "1" },
    {
        "totalArea": "遵义",
        "area": "小计", "all": "19", "speed": "1", "nation": "1", "province": "16", "country": "2", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0"
    },
    { "totalArea": "遵义", "area": "红花岗区", "all": "10", "speed": "0", "nation": "0", "province": "9", "country": "1", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "汇川区", "all": "2", "speed": "0", "nation": "0", "province": "1", "country": "1", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "赤水县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "仁怀市", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "遵义县", "all": "3", "speed": "0", "nation": "0", "province": "3", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "桐梓县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "绥阳县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "正安县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "道真县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "务川县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "凤冈县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "湄潭县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "余庆县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "遵义", "area": "习水县", "all": "1", "speed": "1", "nation": "1", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    {
        "totalArea": "安顺",
        "area": "小计",
        "all": "4", "speed": "0", "nation": "0", "province": "3", "country": "1", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0"
    },
    { "totalArea": "安顺", "area": "西秀区", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "安顺", "area": "黄果树开发区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "安顺", "area": "平坝县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "安顺", "area": "普定县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "安顺", "area": "关岭县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "安顺", "area": "镇宁县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "安顺", "area": "紫云县", "all": "2", "speed": "0", "nation": "0", "province": "1", "country": "1", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "安顺", "area": "安顺市开发区", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    {
        "totalArea": "黔南",
        "area": "小计",
        "all": "11", "speed": "0", "nation": "0", "province": "7", "country": "3", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "1"
    },
    { "totalArea": "黔南", "area": "都匀市", "all": "5", "speed": "0", "nation": "0", "province": "2", "country": "3", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔南", "area": "福泉市", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔南", "area": "荔波县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔南", "area": "贵定县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔南", "area": "瓮安县", "all": "3", "speed": "0", "nation": "0", "province": "2", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "1" },
    { "totalArea": "黔南", "area": "独山县", "all": "2", "speed": "0", "nation": "0", "province": "2", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔南", "area": "平塘县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔南", "area": "罗甸县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔南", "area": "长顺县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔南", "area": "龙里县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔南", "area": "惠水县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔南", "area": "三都县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    {
        "totalArea": "黔东南",
        "area": "小计",
        "all": "3", "speed": "0", "nation": "0", "province": "3", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0"
    },
    { "totalArea": "黔东南", "area": "凯里市", "all": "2", "speed": "0", "nation": "0", "province": "2", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "黄平县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "施秉县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "三穗县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "镇远县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "岑巩县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "天柱县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "锦屏县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "剑河县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "台江县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "黎平县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "榕江县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "从江县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "雷山县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "麻江县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "丹寨县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔东南", "area": "经济开发区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    {
        "totalArea": "铜仁",
        "area": "小计",
        "all": "2", "speed": "1", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "1", "corrosives": "1", "oxygen": "0"
    },
    { "totalArea": "铜仁", "area": "铜仁市", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "铜仁", "area": "万山特区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "1", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "铜仁", "area": "江口县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "铜仁", "area": "玉屏县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "铜仁", "area": "石阡县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "1", "oxygen": "0" },
    { "totalArea": "铜仁", "area": "思南县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "铜仁", "area": "印江县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "铜仁", "area": "德江县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "铜仁", "area": "沿河县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "铜仁", "area": "松桃县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "铜仁", "area": "大龙经济开发区", "all": "1", "speed": "1", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    {
        "totalArea": "毕节",
        "area": "小计",
        "all": "6", "speed": "1", "nation": "0", "province": "3", "country": "2", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0"
    },
    { "totalArea": "毕节", "area": "七星关区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "毕节", "area": "毕节市", "all": "5", "speed": "1", "nation": "0", "province": "3", "country": "1", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "毕节", "area": "大方县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "毕节", "area": "黔西县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "毕节", "area": "金沙县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "毕节", "area": "织金县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "毕节", "area": "纳雍县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "毕节", "area": "威宁县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "毕节", "area": "赫章县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    {
        "totalArea": "六盘水",
        "area": "小计",
        "all": "20", "speed": "0", "nation": "0", "province": "19", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "1"
    },
    { "totalArea": "六盘水", "area": "钟山区", "all": "10", "speed": "0", "nation": "0", "province": "10", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "六盘水", "area": "六枝特区", "all": "3", "speed": "0", "nation": "0", "province": "3", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "六盘水", "area": "水城县", "all": "6", "speed": "0", "nation": "0", "province": "5", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "1" },
    { "totalArea": "六盘水", "area": "盘县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "六盘水", "area": "红桥新区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    {
        "totalArea": "黔西南",
        "area": "小计",
        "all": "4", "speed": "0", "nation": "0", "province": "3", "country": "1", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0"
    },
    { "totalArea": "黔西南", "area": "兴义市", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔西南", "area": "顶效开发区", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔西南", "area": "兴仁县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔西南", "area": "普安县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔西南", "area": "晴隆县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔西南", "area": "贞丰县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔西南", "area": "望漠县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔西南", "area": "册亨县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "黔西南", "area": "安龙县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    {
        "totalArea": "贵安",
        "area": "小计",
        "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0"
    },
    { "totalArea": "贵安", "area": "湖潮乡", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "贵安", "area": "党武镇", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "贵安", "area": "高峰镇", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
    { "totalArea": "贵安", "area": "马场镇", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "corrosives": "0", "oxygen": "0" },
]
savePeploeData = [
    { "totalArea": "2019年全省合计", "area": "2019年全省合计", "all": "3086", "speed": "970", "nation": "25", "province": "901", "country": "582", "city": "608" },
    { "totalArea": "贵阳", "area": "小计", "all": "1459", "speed": "720", "nation": "5", "province": "534", "country": "170", "city": "248" },
    { "totalArea": "贵阳", "area": "南明区", "all": "526", "speed": "198", "nation": "0", "province": "182", "country": "34", "city": "112" },
    { "totalArea": "贵阳", "area": "云岩区", "all": "296", "speed": "168", "nation": "0", "province": "89", "country": "15", "city": "24" },
    { "totalArea": "贵阳", "area": "清镇市", "all": "120", "speed": "35", "nation": "4", "province": "34", "country": "22", "city": "25" },
    { "totalArea": "贵阳", "area": "花溪区", "all": "111", "speed": "38", "nation": "0", "province": "38", "country": "24", "city": "11" },
    { "totalArea": "贵阳", "area": "乌当区", "all": "93", "speed": "29", "nation": "1", "province": "45", "country": "7", "city": "11" },
    { "totalArea": "贵阳", "area": "白云区", "all": "30", "speed": "6", "nation": "1", "province": "1", "country": "8", "city": "14" },
    { "totalArea": "贵阳", "area": "经开区", "all": "9", "speed": "1", "nation": "0", "province": "4", "country": "0", "city": "4" },
    { "totalArea": "贵阳", "area": "开阳县", "all": "58", "speed": "14", "nation": "0", "province": "6", "country": "26", "city": "12" },
    { "totalArea": "贵阳", "area": "息烽县", "all": "25", "speed": "8", "nation": "0", "province": "8", "country": "3", "city": "6" },
    { "totalArea": "贵阳", "area": "修文县", "all": "40", "speed": "9", "nation": "0", "province": "12", "country": "11", "city": "8" },
    { "totalArea": "贵阳", "area": "金阳", "all": "218", "speed": "97", "nation": "0", "province": "82", "country": "10", "city": "29" },

    { "totalArea": "遵义", "area": "小计", "all": "475", "speed": "136", "nation": "7", "province": "134", "country": "89", "city": "109" },
    { "totalArea": "遵义", "area": "红花岗区", "all": "139", "speed": "54", "nation": "1", "province": "44", "country": "25", "city": "15" },
    { "totalArea": "遵义", "area": "汇川区", "all": "79", "speed": "32", "nation": "1", "province": "25", "country": "7", "city": "14" },
    { "totalArea": "遵义", "area": "赤水县", "all": "15", "speed": "1", "nation": "1", "province": "2", "country": "3", "city": "8" },
    { "totalArea": "遵义", "area": "仁怀市", "all": "56", "speed": "9", "nation": "1", "province": "23", "country": "7", "city": "16" },
    { "totalArea": "遵义", "area": "遵义县", "all": "31", "speed": "4", "nation": "1", "province": "12", "country": "5", "city": "9" },
    { "totalArea": "遵义", "area": "桐梓县", "all": "25", "speed": "7", "nation": "0", "province": "8", "country": "4", "city": "6" },
    { "totalArea": "遵义", "area": "绥阳县", "all": "20", "speed": "3", "nation": "0", "province": "5", "country": "4", "city": "8" },
    { "totalArea": "遵义", "area": "正安县", "all": "9", "speed": "1", "nation": "1", "province": "2", "country": "3", "city": "2" },
    { "totalArea": "遵义", "area": "道真县", "all": "8", "speed": "4", "nation": "0", "province": "0", "country": "1", "city": "3" },
    { "totalArea": "遵义", "area": "务川县", "all": "6", "speed": "1", "nation": "0", "province": "1", "country": "2", "city": "2" },
    { "totalArea": "遵义", "area": "凤冈县", "all": "18", "speed": "4", "nation": "1", "province": "1", "country": "5", "city": "7" },
    { "totalArea": "遵义", "area": "湄潭县", "all": "31", "speed": "4", "nation": "0", "province": "3", "country": "15", "city": "9" },
    { "totalArea": "遵义", "area": "余庆县", "all": "14", "speed": "6", "nation": "0", "province": "2", "country": "4", "city": "2" },
    { "totalArea": "遵义", "area": "习水县", "all": "24", "speed": "6", "nation": "0", "province": "6", "country": "4", "city": "8" },

    { "totalArea": "安顺", "area": "小计", "all": "93", "speed": "13", "nation": "0", "province": "32", "country": "29", "city": "19" },
    { "totalArea": "安顺", "area": "西秀区", "all": "56", "speed": "3", "nation": "0", "province": "21", "country": "21", "city": "11" },
    { "totalArea": "安顺", "area": "黄果树开发区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "安顺", "area": "平坝县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "安顺", "area": "普定县", "all": "2", "speed": "2", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "安顺", "area": "关岭县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "安顺", "area": "镇宁县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "1" },
    { "totalArea": "安顺", "area": "紫云县", "all": "12", "speed": "1", "nation": "0", "province": "3", "country": "5", "city": "3" },
    { "totalArea": "安顺", "area": "安顺市开发区", "all": "22", "speed": "7", "nation": "0", "province": "8", "country": "3", "city": "4" },


    { "totalArea": "黔南", "area": "小计", "all": "144", "speed": "10", "nation": "0", "province": "33", "country": "68", "city": "33" },
    { "totalArea": "黔南", "area": "都匀市", "all": "31", "speed": "5", "nation": "0", "province": "6", "country": "11", "city": "9" },
    { "totalArea": "黔南", "area": "福泉市", "all": "6", "speed": "0", "nation": "0", "province": "2", "country": "3", "city": "1" },
    { "totalArea": "黔南", "area": "荔波县", "all": "17", "speed": "1", "nation": "0", "province": "6", "country": "7", "city": "3" },
    { "totalArea": "黔南", "area": "贵定县", "all": "26", "speed": "1", "nation": "0", "province": "7", "country": "8", "city": "10" },
    { "totalArea": "黔南", "area": "瓮安县", "all": "4", "speed": "0", "nation": "0", "province": "2", "country": "0", "city": "2" },
    { "totalArea": "黔南", "area": "独山县", "all": "5", "speed": "0", "nation": "0", "province": "2", "country": "2", "city": "1" },
    { "totalArea": "黔南", "area": "平塘县", "all": "10", "speed": "0", "nation": "0", "province": "1", "country": "8", "city": "1" },
    { "totalArea": "黔南", "area": "罗甸县", "all": "13", "speed": "0", "nation": "0", "province": "2", "country": "8", "city": "3" },
    { "totalArea": "黔南", "area": "长顺县", "all": "8", "speed": "0", "nation": "0", "province": "0", "country": "6", "city": "2" },
    { "totalArea": "黔南", "area": "龙里县", "all": "3", "speed": "1", "nation": "0", "province": "0", "country": "2", "city": "0" },
    { "totalArea": "黔南", "area": "惠水县", "all": "6", "speed": "0", "nation": "0", "province": "1", "country": "5", "city": "0" },
    { "totalArea": "黔南", "area": "三都县", "all": "15", "speed": "2", "nation": "0", "province": "4", "country": "8", "city": "1" },



    { "totalArea": "黔东南", "area": "小计", "all": "95", "speed": "21", "nation": "3", "province": "13", "country": "27", "city": "31" },
    { "totalArea": "黔东南", "area": "凯里市", "all": "39", "speed": "13", "nation": "2", "province": "5", "country": "6", "city": "13" },
    { "totalArea": "黔东南", "area": "黄平县", "all": "3", "speed": "1", "nation": "1", "province": "1", "country": "0", "city": "0" },
    { "totalArea": "黔东南", "area": "施秉县", "all": "7", "speed": "1", "nation": "0", "province": "1", "country": "2", "city": "3" },
    { "totalArea": "黔东南", "area": "三穗县", "all": "2", "speed": "1", "nation": "0", "province": "0", "country": "1", "city": "0" },
    { "totalArea": "黔东南", "area": "镇远县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "黔东南", "area": "岑巩县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "1" },
    { "totalArea": "黔东南", "area": "天柱县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "黔东南", "area": "锦屏县", "all": "3", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "2" },
    { "totalArea": "黔东南", "area": "剑河县", "all": "3", "speed": "1", "nation": "0", "province": "0", "country": "1", "city": "1" },
    { "totalArea": "黔东南", "area": "台江县", "all": "4", "speed": "0", "nation": "0", "province": "0", "country": "3", "city": "1" },
    { "totalArea": "黔东南", "area": "黎平县", "all": "8", "speed": "3", "nation": "0", "province": "2", "country": "1", "city": "2" },
    { "totalArea": "黔东南", "area": "榕江县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0" },
    { "totalArea": "黔东南", "area": "从江县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0" },
    { "totalArea": "黔东南", "area": "雷山县", "all": "3", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "3" },
    { "totalArea": "黔东南", "area": "麻江县", "all": "2", "speed": "0", "nation": "0", "province": "1", "country": "1", "city": "0" },
    { "totalArea": "黔东南", "area": "丹寨县", "all": "6", "speed": "1", "nation": "0", "province": "1", "country": "1", "city": "3" },
    { "totalArea": "黔东南", "area": "经济开发区", "all": "12", "speed": "0", "nation": "0", "province": "2", "country": "8", "city": "2" },

    { "totalArea": "铜仁", "area": "小计", "all": "108", "speed": "9", "nation": "1", "province": "21", "country": "43", "city": "34" },
    { "totalArea": "铜仁", "area": "铜仁市", "all": "33", "speed": "2", "nation": "1", "province": "6", "country": "15", "city": "9" },
    { "totalArea": "铜仁", "area": "万山特区", "all": "5", "speed": "0", "nation": "0", "province": "2", "country": "1", "city": "2" },
    { "totalArea": "铜仁", "area": "江口县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "1" },
    { "totalArea": "铜仁", "area": "玉屏县", "all": "4", "speed": "0", "nation": "0", "province": "2", "country": "", "city": "2" },
    { "totalArea": "铜仁", "area": "石阡县", "all": "9", "speed": "2", "nation": "0", "province": "1", "country": "2", "city": "4" },
    { "totalArea": "铜仁", "area": "思南县", "all": "7", "speed": "0", "nation": "0", "province": "0", "country": "6", "city": "1" },
    { "totalArea": "铜仁", "area": "印江县", "all": "7", "speed": "0", "nation": "0", "province": "2", "country": "5", "city": "0" },
    { "totalArea": "铜仁", "area": "德江县", "all": "20", "speed": "3", "nation": "0", "province": "5", "country": "5", "city": "7" },
    { "totalArea": "铜仁", "area": "沿河县", "all": "7", "speed": "1", "nation": "0", "province": "1", "country": "3", "city": "2" },
    { "totalArea": "铜仁", "area": "松桃县", "all": "9", "speed": "1", "nation": "0", "province": "1", "country": "3", "city": "4" },
    { "totalArea": "铜仁", "area": "大龙经济开发区", "all": "6", "speed": "0", "nation": "0", "province": "1", "country": "3", "city": "2" },

    { "totalArea": "毕节", "area": "小计", "all": "118", "speed": "12", "nation": "1", "province": "32", "country": "39", "city": "34" },
    { "totalArea": "毕节", "area": "七星关区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0" },
    { "totalArea": "毕节", "area": "毕节市", "all": "65", "speed": "10", "nation": "1", "province": "22", "country": "17", "city": "15" },
    { "totalArea": "毕节", "area": "大方县", "all": "8", "speed": "0", "nation": "0", "province": "2", "country": "4", "city": "2" },
    { "totalArea": "毕节", "area": "黔西县", "all": "7", "speed": "2", "nation": "0", "province": "3", "country": "2", "city": "" },
    { "totalArea": "毕节", "area": "金沙县", "all": "3", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "2" },
    { "totalArea": "毕节", "area": "织金县", "all": "15", "speed": "0", "nation": "0", "province": "2", "country": "9", "city": "4" },
    { "totalArea": "毕节", "area": "纳雍县", "all": "6", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "5" },
    { "totalArea": "毕节", "area": "威宁县", "all": "7", "speed": "0", "nation": "0", "province": "0", "country": "2", "city": "5" },
    { "totalArea": "毕节", "area": "赫章县", "all": "7", "speed": "0", "nation": "0", "province": "3", "country": "3", "city": "1" },


    { "totalArea": "六盘水", "area": "小计", "all": "182", "speed": "25", "nation": "8", "province": "63", "country": "45", "city": "41" },
    { "totalArea": "六盘水", "area": "钟山区", "all": "79", "speed": "19", "nation": "0", "province": "29", "country": "19", "city": "12" },
    { "totalArea": "六盘水", "area": "六枝特区", "all": "13", "speed": "1", "nation": "3", "province": "3", "country": "3", "city": "3" },
    { "totalArea": "六盘水", "area": "水城县", "all": "34", "speed": "0", "nation": "2", "province": "10", "country": "10", "city": "12" },
    { "totalArea": "六盘水", "area": "盘县", "all": "50", "speed": "5", "nation": "3", "province": "20", "country": "11", "city": "11" },
    { "totalArea": "六盘水", "area": "红桥新区", "all": "6", "speed": "0", "nation": "0", "province": "1", "country": "2", "city": "3" },

    { "totalArea": "黔西南", "area": "小计", "all": "181", "speed": "23", "nation": "0", "province": "32", "country": "67", "city": "59" },
    { "totalArea": "黔西南", "area": "兴义市", "all": "54", "speed": "13", "nation": "0", "province": "10", "country": "14", "city": "17" },
    { "totalArea": "黔西南", "area": "顶效开发区", "all": "8", "speed": "0", "nation": "0", "province": "2", "country": "1", "city": "5" },
    { "totalArea": "黔西南", "area": "兴仁县", "all": "22", "speed": "1", "nation": "0", "province": "3", "country": "8", "city": "10" },
    { "totalArea": "黔西南", "area": "普安县", "all": "10", "speed": "0", "nation": "0", "province": "1", "country": "6", "city": "3" },
    { "totalArea": "黔西南", "area": "晴隆县", "all": "14", "speed": "1", "nation": "0", "province": "4", "country": "9", "city": "0" },
    { "totalArea": "黔西南", "area": "贞丰县", "all": "25", "speed": "2", "nation": "0", "province": "4", "country": "14", "city": "5" },
    { "totalArea": "黔西南", "area": "望漠县", "all": "12", "speed": "3", "nation": "0", "province": "2", "country": "4", "city": "3" },
    { "totalArea": "黔西南", "area": "册亨县", "all": "9", "speed": "0", "nation": "0", "province": "3", "country": "4", "city": "2" },
    { "totalArea": "黔西南", "area": "安龙县", "all": "27", "speed": "3", "nation": "0", "province": "3", "country": "7", "city": "14" },

    { "totalArea": "贵安", "area": "小计", "all": "13", "speed": "1", "nation": "0", "province": "7", "country": "5", "city": "0" },
    { "totalArea": "贵安", "area": "湖潮乡", "all": "4", "speed": "0", "nation": "0", "province": "3", "country": "1", "city": "0" },
    { "totalArea": "贵安", "area": "党武镇", "all": "5", "speed": "0", "nation": "0", "province": "4", "country": "1", "city": "0" },
    { "totalArea": "贵安", "area": "高峰镇", "all": "3", "speed": "1", "nation": "0", "province": "0", "country": "2", "city": "0" },
    { "totalArea": "贵安", "area": "马场镇", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0" },
]
natureData = [
    { "totalArea": "2019年全省合计 ", "area": "2019年全省合计", "all": "343", "speed": "1", "nation": "278", },
    { "totalArea": "贵阳", "area": "小计", "all": "164", "speed": "0", "nation": "143", },
    { "totalArea": "贵阳", "area": "南明区", "all": "28", "speed": "0", "nation": "26", },
    { "totalArea": "贵阳", "area": "云岩区", "all": "40", "speed": "0", "nation": "30", },
    { "totalArea": "贵阳", "area": "清镇市", "all": "18", "speed": "0", "nation": "17", },
    { "totalArea": "贵阳", "area": "花溪区", "all": "13", "speed": "0", "nation": "12", },
    { "totalArea": "贵阳", "area": "乌当区", "all": "15", "speed": "0", "nation": "15" },
    { "totalArea": "贵阳", "area": "白云区", "all": "3", "speed": "0", "nation": "3", },
    { "totalArea": "贵阳", "area": "经开区", "all": "0", "speed": "0", "nation": "0" },
    { "totalArea": "贵阳", "area": "开阳县", "all": "6", "speed": "0", "nation": "5", },
    { "totalArea": "贵阳", "area": "息烽县", "all": "3", "speed": "0", "nation": "2", },
    { "totalArea": "贵阳", "area": "修文县", "all": "5", "speed": "0", "nation": "4", },
    { "totalArea": "贵阳", "area": "金阳", "all": "26", "speed": "0", "nation": "23", },
    { "totalArea": "贵阳", "area": "小河区", "all": "7", "speed": "0", "nation": "6", },
    { "totalArea": "贵阳", "area": "观山湖区", "all": "0", "speed": "0", "nation": "0" },

    { "totalArea": "遵义", "area": "小计", "all": "27", "speed": "0", "nation": "24", },
    { "totalArea": "遵义", "area": "红花岗区", "all": "5", "speed": "0", "nation": "4", },
    { "totalArea": "遵义", "area": "汇川区", "all": "8", "speed": "0", "nation": "8", },
    { "totalArea": "遵义", "area": "赤水县", "all": "1", "speed": "0", "nation": "1", },
    { "totalArea": "遵义", "area": "新浦区", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "遵义", "area": "仁怀市", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "遵义", "area": "播州区", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "遵义", "area": "桐梓县", "all": "2", "speed": "0", "nation": "1", },
    { "totalArea": "遵义", "area": "绥阳县", "all": "3", "speed": "0", "nation": "2", },
    { "totalArea": "遵义", "area": "正安县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "遵义", "area": "道真县", "all": "1", "speed": "0", "nation": "1", },
    { "totalArea": "遵义", "area": "务川县", "all": "0", "speed": "0", "nation": "", },
    { "totalArea": "遵义", "area": "凤冈县", "all": "5", "speed": "0", "nation": "5", },
    { "totalArea": "遵义", "area": "湄潭县", "all": "0", "speed": "0", "nation": "", },
    { "totalArea": "遵义", "area": "余庆县", "all": "1", "speed": "0", "nation": "1", },
    { "totalArea": "遵义", "area": "习水县", "all": "1", "speed": "0", "nation": "1", },

    { "totalArea": "安顺", "area": "小计", "all": "11", "speed": "0", "nation": "11", },
    { "totalArea": "安顺", "area": "西秀区", "all": "7", "speed": "0", "nation": "7", },
    { "totalArea": "安顺", "area": "黄果树开发区", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "安顺", "area": "平坝县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "安顺", "area": "普定县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "安顺", "area": "关岭县", "all": "1", "speed": "0", "nation": "1", },
    { "totalArea": "安顺", "area": "镇宁县", "all": "1", "speed": "0", "nation": "1", },
    { "totalArea": "安顺", "area": "紫云县", "all": "2", "speed": "0", "nation": "2", },
    { "totalArea": "安顺", "area": "安顺市开发区", "all": "0", "speed": "0", "nation": "0", },




    { "totalArea": "黔南", "area": "小计", "all": "12", "speed": "0", "nation": "9" },
    { "totalArea": "黔南", "area": "都匀市", "all": "1", "speed": "0", "nation": "1" },
    { "totalArea": "黔南", "area": "福泉市", "all": "1", "speed": "0", "nation": "1" },
    { "totalArea": "黔南", "area": "荔波县", "all": "0", "speed": "0", "nation": "0" },
    { "totalArea": "黔南", "area": "贵定县", "all": "2", "speed": "0", "nation": "2" },
    { "totalArea": "黔南", "area": "瓮安县", "all": "0", "speed": "0", "nation": "0" },
    { "totalArea": "黔南", "area": "独山县", "all": "1", "speed": "0", "nation": "1" },
    { "totalArea": "黔南", "area": "平塘县", "all": "0", "speed": "0", "nation": "0" },
    { "totalArea": "黔南", "area": "罗甸县", "all": "3", "speed": "0", "nation": "1" },
    { "totalArea": "黔南", "area": "长顺县", "all": "2", "speed": "0", "nation": "1" },
    { "totalArea": "黔南", "area": "龙里县", "all": "0", "speed": "0", "nation": "0" },
    { "totalArea": "黔南", "area": "惠水县", "all": "1", "speed": "0", "nation": "1" },
    { "totalArea": "黔南", "area": "三都县", "all": "1", "speed": "0", "nation": "1" },



    { "totalArea": "黔东南", "area": "小计", "all": "20", "speed": "0", "nation": "14", },
    { "totalArea": "黔东南", "area": "凯里市", "all": "2", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "黄平县", "all": "1", "speed": "0", "nation": "1", },
    { "totalArea": "黔东南", "area": "施秉县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "三穗县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "镇远县", "all": "5", "speed": "0", "nation": "5", },
    { "totalArea": "黔东南", "area": "岑巩县", "all": "1", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "天柱县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "锦屏县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "剑河县", "all": "2", "speed": "0", "nation": "2", },
    { "totalArea": "黔东南", "area": "台江县", "all": "3", "speed": "0", "nation": "3", },
    { "totalArea": "黔东南", "area": "黎平县", "all": "1", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "榕江县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "从江县", "all": "1", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "雷山县", "all": "1", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "麻江县", "all": "3", "speed": "0", "nation": "3", },
    { "totalArea": "黔东南", "area": "丹寨县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "黔东南", "area": "经济开发区", "all": "0", "speed": "0", "nation": "0", },

    { "totalArea": "铜仁", "area": "铜仁市", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "铜仁", "area": "万山特区", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "铜仁", "area": "江口县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "铜仁", "area": "玉屏县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "铜仁", "area": "石阡县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "铜仁", "area": "思南县", "all": "1", "speed": "0", "nation": "0", },
    { "totalArea": "铜仁", "area": "印江县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "铜仁", "area": "德江县", "all": "4", "speed": "0", "nation": "4", },
    { "totalArea": "铜仁", "area": "沿河县", "all": "4", "speed": "1", "nation": "3", },
    { "totalArea": "铜仁", "area": "松桃县", "all": "3", "speed": "0", "nation": "0", },
    { "totalArea": "铜仁", "area": "大龙经济开发区", "all": "0", "speed": "0", "nation": "0", },

    { "totalArea": "毕节", "area": "小计", "all": "31", "speed": "0", "nation": "25", },
    { "totalArea": "毕节", "area": "毕节市", "all": "17", "speed": "0", "nation": "16", },
    { "totalArea": "毕节", "area": "七星关区", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "毕节", "area": "大方县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "毕节", "area": "黔西县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "毕节", "area": "金沙县", "all": "1", "speed": "0", "nation": "1", },
    { "totalArea": "毕节", "area": "织金县", "all": "2", "speed": "0", "nation": "1", },
    { "totalArea": "毕节", "area": "纳雍县", "all": "3", "speed": "0", "nation": "2", },
    { "totalArea": "毕节", "area": "威宁县", "all": "4", "speed": "0", "nation": "3", },
    { "totalArea": "毕节", "area": "赫章县", "all": "4", "speed": "0", "nation": "2", },


    { "totalArea": "六盘水", "area": "小计", "all": "19", "speed": "0", "nation": "8", },
    { "totalArea": "六盘水", "area": "钟山区", "all": "3", "speed": "0", "nation": "3", },
    { "totalArea": "六盘水", "area": "六枝特区", "all": "3", "speed": "0", "nation": "3", },
    { "totalArea": "六盘水", "area": "水城县", "all": "7", "speed": "0", "nation": "0", },
    { "totalArea": "六盘水", "area": "盘县", "all": "6", "speed": "0", "nation": "2", },
    { "totalArea": "六盘水", "area": "红桥新区", "all": "0", "speed": "0", "nation": "0", },

    { "totalArea": "黔西南", "area": "小计", "all": "43", "speed": "0", "nation": "37", },
    { "totalArea": "黔西南", "area": "兴义市", "all": "9", "speed": "0", "nation": "8", },
    { "totalArea": "黔西南", "area": "顶效开发区", "all": "2", "speed": "0", "nation": "2", },
    { "totalArea": "黔西南", "area": "兴仁县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "黔西南", "area": "普安县", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "黔西南", "area": "晴隆县", "all": "3", "speed": "0", "nation": "3", },
    { "totalArea": "黔西南", "area": "贞丰县", "all": "12", "speed": "0", "nation": "11", },
    { "totalArea": "黔西南", "area": "望漠县", "all": "4", "speed": "0", "nation": "3", },
    { "totalArea": "黔西南", "area": "册亨县", "all": "4", "speed": "0", "nation": "4", },
    { "totalArea": "黔西南", "area": "安龙县", "all": "9", "speed": "0", "nation": "6", },

    { "totalArea": "贵安", "area": "小计", "all": "4", "speed": "0", "nation": "0", },
    { "totalArea": "贵安", "area": "湖潮乡", "all": "1", "speed": "0", "nation": "0", },
    { "totalArea": "贵安", "area": "党武镇", "all": "2", "speed": "0", "nation": "0", },
    { "totalArea": "贵安", "area": "高峰镇", "all": "0", "speed": "0", "nation": "0", },
    { "totalArea": "贵安", "area": "马场镇", "all": "1", "speed": "0", "nation": "0", },

]
// 化学危险品分析
chemistryData = [
    { "totalArea": "2019年全省合计 ", "area": "2019年全省合计", "all": "343", "speed": "1", "nation": "278", "province": "3", "country": "33", "city": "0", "fire": "28" },
    { "totalArea": "贵阳", "area": "小计", "all": "139", "speed": "1", "nation": "0", "province": "88", "country": "35", "city": "3", "fire": "0", "aaa": "0", "bbb": "6" },
    { "totalArea": "贵阳", "area": "南明区", "all": "34", "speed": "1", "nation": "0", "province": "27", "country": "4", "city": "0", "fire": "0", "aaa": "0", "bbb": "2" },
    { "totalArea": "贵阳", "area": "云岩区", "all": "26", "speed": "0", "nation": "0", "province": "17", "country": "9", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵阳", "area": "清镇市", "all": "7", "speed": "0", "nation": "0", "province": "6", "country": "0", "city": "1", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵阳", "area": "花溪区", "all": "13", "speed": "0", "nation": "0", "province": "5", "country": "8", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵阳", "area": "乌当区", "all": "4", "speed": "0", "nation": "0", "province": "2", "country": "2", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵阳", "area": "白云区", "all": "15", "speed": "0", "nation": "0", "province": "8", "country": "5", "city": "2", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵阳", "area": "小河区", "all": "8", "speed": "0", "nation": "0", "province": "5", "country": "2", "city": "0", "fire": "0", "aaa": "0", "bbb": "1" },
    { "totalArea": "贵阳", "area": "开阳县", "all": "4", "speed": "0", "nation": "0", "province": "2", "country": "2", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵阳", "area": "息烽县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵阳", "area": "修文县", "all": "7", "speed": "0", "nation": "0", "province": "5", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "2" },
    { "totalArea": "贵阳", "area": "金阳", "all": "0", "speed": "0", "nation": "0", "province": "11", "country": "2", "city": "0", "fire": "0", "aaa": "0", "bbb": "1" },
    { "totalArea": "遵义", "area": "小计", "all": "19", "speed": "1", "nation": "1", "province": "16", "country": "2", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "红花岗区", "all": "10", "speed": "0", "nation": "0", "province": "9", "country": "1", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "汇川区", "all": "2", "speed": "0", "nation": "0", "province": "1", "country": "1", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "赤水县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "仁怀市", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "遵义县", "all": "3", "speed": "0", "nation": "0", "province": "3", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "桐梓县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "绥阳县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "正安县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "道真县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "务川县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "凤冈县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "湄潭县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "余庆县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "遵义", "area": "习水县", "all": "1", "speed": "1", "nation": "1", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "安顺", "area": "小计", "all": "4", "speed": "0", "nation": "0", "province": "3", "country": "1", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "安顺", "area": "西秀区", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "安顺", "area": "黄果树开发区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "安顺", "area": "平坝县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "安顺", "area": "普定县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "1", "bbb": "0" },
    { "totalArea": "安顺", "area": "关岭县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "安顺", "area": "镇宁县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "安顺", "area": "紫云县", "all": "2", "speed": "0", "nation": "0", "province": "1", "country": "1", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "安顺", "area": "安顺市开发区", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "小计", "all": "11", "speed": "0", "nation": "0", "province": "7", "country": "3", "city": "0", "fire": "0", "aaa": "0", "bbb": "1" },
    { "totalArea": "黔南", "area": "都匀市", "all": "5", "speed": "0", "nation": "0", "province": "2", "country": "3", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "福泉市", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "荔波县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "贵定县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "瓮安县", "all": "3", "speed": "0", "nation": "0", "province": "2", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "1" },
    { "totalArea": "黔南", "area": "独山县", "all": "2", "speed": "0", "nation": "0", "province": "2", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "平塘县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "罗甸县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "长顺县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "龙里县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "惠水县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔南", "area": "三都县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "小计", "all": "3", "speed": "0", "nation": "0", "province": "3", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "凯里市", "all": "2", "speed": "0", "nation": "0", "province": "2", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "黄平县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "施秉县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "三穗县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "镇远县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "岑巩县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "天柱县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "锦屏县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "剑河县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "台江县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "1", "bbb": "0" },
    { "totalArea": "黔东南", "area": "黎平县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "榕江县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "从江县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "雷山县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "麻江县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "丹寨县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔东南", "area": "经济开发区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "铜仁", "area": "小计", "all": "2", "speed": "1", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "1", "aaa": "1", "bbb": "0" },
    { "totalArea": "铜仁", "area": "铜仁市", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "铜仁", "area": "万山特区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "1", "aaa": "0", "bbb": "0" },
    { "totalArea": "铜仁", "area": "江口县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "铜仁", "area": "玉屏县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "铜仁", "area": "石阡县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "1", "bbb": "0" },
    { "totalArea": "铜仁", "area": "思南县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "铜仁", "area": "印江县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "铜仁", "area": "德江县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "铜仁", "area": "沿河县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "铜仁", "area": "松桃县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "铜仁", "area": "大龙经济开发区", "all": "1", "speed": "1", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "毕节", "area": "小计", "all": "6", "speed": "1", "nation": "0", "province": "3", "country": "2", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "毕节", "area": "七星关区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "毕节", "area": "毕节市", "all": "5", "speed": "1", "nation": "0", "province": "3", "country": "1", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "毕节", "area": "大方县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "毕节", "area": "黔西县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "毕节", "area": "金沙县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "毕节", "area": "织金县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "毕节", "area": "纳雍县", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "毕节", "area": "威宁县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "毕节", "area": "赫章县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "六盘水", "area": "小计", "all": "20", "speed": "0", "nation": "0", "province": "19", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "1" },
    { "totalArea": "六盘水", "area": "钟山区", "all": "10", "speed": "0", "nation": "0", "province": "10", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "六盘水", "area": "六枝特区", "all": "3", "speed": "0", "nation": "0", "province": "3", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "六盘水", "area": "水城县", "all": "6", "speed": "0", "nation": "0", "province": "5", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "1" },
    { "totalArea": "六盘水", "area": "盘县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "六盘水", "area": "红桥新区", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔西南", "area": "小计", "all": "4", "speed": "0", "nation": "0", "province": "3", "country": "1", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔西南", "area": "兴义市", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔西南", "area": "顶效开发区", "all": "1", "speed": "0", "nation": "0", "province": "0", "country": "1", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔西南", "area": "兴仁县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔西南", "area": "普安县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔西南", "area": "晴隆县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔西南", "area": "贞丰县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔西南", "area": "望漠县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔西南", "area": "册亨县", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "黔西南", "area": "安龙县", "all": "1", "speed": "0", "nation": "0", "province": "1", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵安", "area": "小计", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵安", "area": "湖潮乡", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵安", "area": "党武镇", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵安", "area": "高峰镇", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },
    { "totalArea": "贵安", "area": "马场镇", "all": "0", "speed": "0", "nation": "0", "province": "0", "country": "0", "city": "0", "fire": "0", "aaa": "0", "bbb": "0" },

]
var data = {
    dangerData,
    trafficeData,
    savePeploeData,
    natureData,
    chemistryData
}
export default data;